Repository ReOpenSG/ReOpenSG, pull requests merged in 2023-12, with the labels that each got.

#18 [History] HistorySwiper, HistorySlide, YearSlide 컴포넌트 초안
  .eslintrc.cjs
  .eslintrc.json
  historyData.json
  package-lock.json
  package.json
  postcss.config.js
  src/assets/history_circle.svg
  src/assets/history_circleline.svg
  src/components/History/History.module.css
  src/components/History/HistorySlide.jsx
  src/components/History/HistorySwiper.jsx
  src/components/History/YearSlide.jsx
  src/views/History.jsx
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&css, ➕ Add, D-2

#23 [Industries] Side Nav 컴포넌트와 산업 특징, 산업 관련 제품 컴포넌트 초안
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/Industries/Char.jsx
  src/components/Industries/Industries.module.css
  src/components/Industries/Product.jsx
  src/components/Industries/Snb.jsx
  src/data/industriesData.js
  src/data/solutionsData.json
  src/routes/routes.jsx
  src/views/Industries.jsx
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&css, ➕ Add, D-3

#22 [Solutions] Local&Side Nav 컴포넌트와 제품 및 특징, 기능, 기대효과 컴포넌트 초안
  .eslintrc.cjs
  src/components/Solutions/Char.jsx
  src/components/Solutions/Effect.jsx
  src/components/Solutions/Func.jsx
  src/components/Solutions/Lnb.jsx
  src/components/Solutions/Snb.jsx
  src/components/Solutions/Solutions.module.css
  src/components/Solutions/SoultionBanner.jsx
  src/layout/RootLayout.jsx
  src/routes/routes.jsx
  src/views/Solutions.jsx
Labels: ✨ Feature, 🎨 Html&css, ➕ Add, D-3

#33 [Library] LibraryTitle, Download 컴포넌트 초안
  src/assets/library_compabyBrochure_ko.pdf
  src/assets/library_companyBrochure_en.pdf
  src/assets/library_companyProfile_en.pdf
  src/assets/library_companyProfile_ko.pdf
  src/components/Library/DownloadCard.jsx
  src/components/Library/DownloadIcon.jsx
  src/components/Library/DownloadSection.jsx
  src/components/Library/Library.module.css
  src/components/Library/LibraryTitleInner.jsx
  src/components/Library/LibraryTitleSection.jsx
  src/views/Library.jsx
Labels: ✨ Feature, 🎨 Html&css, ➕ Add, D-3

#47 [Library] max-width 설정
  src/views/Library.jsx
Labels: ✨ Feature, 🎨 Html&css, ➕ Add, D-3

#48 [Community] 커뮤니티 관련 컴포넌트 초안
  .eslintrc.cjs
  firebase.js
  src/App.jsx
  src/components/Admin/Admin.module.css
  src/components/Common/BannerSection.jsx
  src/components/Community/ButtonSection.jsx
  src/components/Community/Community.module.css
  src/components/Community/CommunityEdit.jsx
  src/components/Community/ContentsSection.jsx
  src/components/Community/InputSection.jsx
  src/components/Community/ListButtons.jsx
  src/components/Community/Notice.jsx
  src/components/Community/NoticeList.jsx
  src/components/Community/NoticeSection.jsx
  src/layout/RootLayout.jsx
  src/main.jsx
  src/recoil/atoms/authStore.js
  src/routes/routes.jsx
  src/views/Admin.jsx
  src/views/Community.jsx
  src/views/CommunityDetail.jsx
  src/views/CommunityForm.jsx
  vite.config.js
Labels: ✨ Feature, 🎨 Html&css, ➕ Add, D-2

#42 [Contact] ContactTitle, Form, 개인정보 활용동의 컴포넌트 + emailJS 연결 초안
  .eslintrc.cjs
  src/assets/react.svg
  src/components/Contact/Agreement.jsx
  src/components/Contact/Contact.module.css
  src/components/Contact/ContactButton.jsx
  src/components/Contact/ContactTitleInner.jsx
  src/components/Contact/ContactTitleSection.jsx
  src/components/Contact/Content.jsx
  src/components/Contact/FillingInput.jsx
  src/components/Contact/InquiryInput.jsx
  src/components/Contact/InquiryType.jsx
  src/components/Contact/PersonalInfo.jsx
  src/components/Contact/icons/ProductIcon.jsx
  src/data/contactData.js
  src/data/emailConfig.js
  src/layout/RootLayout.jsx
  src/views/Contact.jsx
Labels: ✨ Feature, 🎨 Html&css, ➕ Add, D-2

#46 [Footer] 고객문의 링크 연결, 회사 정보 컴포넌트 초안
  src/assets/footer_background.svg
  src/components/Footer/ContactUsSection.jsx
  src/components/Footer/Footer.module.css
  src/components/Footer/MoveButton.jsx
  src/components/Footer/OfficeInfoSection.jsx
  src/layout/Footer.jsx
  src/layout/RootLayout.jsx
Labels: ✨ Feature, 🎨 Html&css, ➕ Add, D-3

#54 [Machines, Devices] Machines, Devices 컴포넌트 및 공통 카드, 설명, 기능 및 특징 컴포넌트 초안
  .gitignore
  netlify.toml
  src/components/MachinesDevices/Card.jsx
  src/components/MachinesDevices/CradsWrapper.jsx
  src/components/MachinesDevices/Desc.jsx
  src/components/MachinesDevices/FuncChar.jsx
  src/components/MachinesDevices/MachinesDevices.module.css
  src/data/devicesData.json
  src/data/machinesData.json
  src/routes/routes.jsx
  src/views/Device.jsx
  src/views/Machines.jsx
  src/views/MachinesDevices.jsx
Labels: ✨ Feature, 🎨 Html&css, ➕ Add, D-2

#60 [Header] Header 컴포넌트 및 메뉴 링크, 데스크탑용 sitemap, 모바일용 sitemap 컴포넌트 초안
  src/assets/header_arrow.svg
  src/assets/header_close.svg
  src/assets/header_hamburger.svg
  src/assets/header_opensg.png
  src/components/Header/AccordionItem.jsx
  src/components/Header/Header.module.css
  src/components/Header/MenuLink.jsx
  src/components/Header/Sitemap.jsx
  src/components/Header/SitemapMobile.jsx
  src/icons/SitemapArrow.jsx
  src/layout/Header.jsx
  src/layout/RootLayout.jsx
Labels: ✨ Feature, 🎨 Html&css, ➕ Add, D-3

#74 [Common] CommonTitle 컴포넌트 초안
  src/components/Common/TitleSection.jsx
  src/components/Common/TitleSection.module.css
Labels: ✨ Feature, 🎨 Html&css, ➕ Add, D-3

#65 [Header] Header 컴포넌트 1차 PR 내용 반영
  src/components/Header/AccordionItem.jsx
  src/components/Header/Sitemap.jsx
  src/components/Header/SitemapMobile.jsx
  src/layout/Header.jsx
  src/layout/RootLayout.jsx
Labels: ✍️ Update, D-3

#75 [Footer] 아이콘 수정 및 font-style 변경
  src/components/Footer/Footer.module.css
  src/components/Footer/MoveButton.jsx
Labels: 🔨 Refactor, 🎨 Html&css, D-3

#78 [Location] Location 컴포넌트 및 LocationPinIcon 컴포넌트, LocationContainer 컴포넌트 초안
  src/assets/location_defaultImage.png
  src/assets/location_link.svg
  src/assets/location_mTower.png
  src/assets/location_map.png
  src/components/Location/Location.module.css
  src/components/Location/LocationContainer.jsx
  src/components/Location/LocationPinIcon.jsx
  src/views/Location.jsx
Labels: ✨ Feature, 🎨 Html&css, ➕ Add, D-3

#77 [Contact] 코드 리팩토링 및 버그 수정
  src/components/Contact/Contact.module.css
  src/components/Contact/ContactTitleInner.jsx
  src/components/Contact/ContactTitleSection.jsx
  src/components/Contact/FillingInput.jsx
  src/components/Contact/InquiryInput.jsx
  src/components/Contact/InquiryType.jsx
  src/components/Contact/PersonalInfo.jsx
  src/utils/debounce.js
  src/views/Contact.jsx
Labels: 🗑️ Delete, 🔨 Refactor, 🔧 fix, 🎨 Html&css, D-3

#81 [Team] CommonTitle 적용 및 IT그룹 직무 데이터 추가
  src/data/teamData.js
  src/views/Team.jsx
Labels: ✍️ Update, D-3

#87 [History] History 컴포넌트 내 이미지 경로 수정
  src/components/History/YearSlide.jsx
Labels: ✍️ Update, 🔧 fix, D-3

#80 [Home] - 스와이퍼, Tag-canvas 기능 추가
  package-lock.json
  package.json
  src/assets/home_industry1.png
  src/assets/home_industry2.png
  src/assets/home_industry3.png
  src/assets/home_industry4.png
  src/assets/home_partner1.png
  src/assets/home_partner2.png
  src/assets/home_partner3.png
  src/assets/home_solutions0.png
  src/assets/home_solutions1.png
  src/assets/home_solutions2.png
  src/assets/home_solutions3.png
  src/assets/home_solutions4.png
  src/assets/home_solutions5.png
  src/assets/home_solutions6.png
  src/assets/home_universe.png
  src/assets/home_universeCircle.png
  src/components/Home/Home.module.css
  src/components/Home/Industries.jsx
  src/components/Home/Keywords.jsx
  src/components/Home/Partner.jsx
  src/components/Home/ProductCard.jsx
  src/components/Home/Products.jsx
  src/components/Home/Solutions.jsx
  src/components/Home/Universe.jsx
  src/views/Home.jsx
  tailwind.config.js
Labels: ✨ Feature, ➕ Add, D-3

#84 [ Header] Header 컴포넌트 내 메뉴 구조 및 링크 경로 수정
  src/components/Header/Sitemap.jsx
  src/components/Header/SitemapMobile.jsx
  src/layout/Header.jsx
  tailwind.config.js
Labels: ✍️ Update, D-3

#76 [Library] 1차 PR 리뷰 사항 반영 및 코드 리팩토링
  src/components/Library/DownloadCard.jsx
  src/components/Library/DownloadSection.jsx
  src/components/Library/Library.module.css
  src/components/Library/LibraryTitleInner.jsx
  src/components/Library/LibraryTitleSection.jsx
  src/views/Library.jsx
Labels: 🗑️ Delete, 🔨 Refactor, 🎨 Html&css, D-1

#86 [Machines, Devices] Machines, Devices 컴포넌트의 타입 분리
  src/assets/devices_HoloLens 2.png
  src/assets/machines_C060D.png
  src/assets/machines_C100D.png
  src/assets/machines_C200.png
  src/assets/machines_C300.png
  src/assets/machines_Fork-Lift Type.png
  src/assets/machines_Foup Type.png
  src/assets/machines_L1000.png
  src/assets/machines_L300.png
  src/assets/machines_P200.png
  src/components/MachinesDevices/Card.jsx
  src/components/MachinesDevices/CradsWrapper.jsx
  src/components/MachinesDevices/Desc.jsx
  src/components/MachinesDevices/FuncChar.jsx
  src/components/MachinesDevices/MachinesDevices.module.css
  src/data/devicesData.json
  src/data/machinesData.json
  src/views/MachinesDevices.jsx
Labels: ✨ Feature, ➕ Add, D-3

#85 [Contact] 코드 리팩토링
  .eslintrc.cjs
  src/components/Contact/Contact.module.css
  src/components/Contact/FillingInput.jsx
  src/components/Contact/PersonalInfo.jsx
Labels: ✨ Feature, ✍️ Update, 🔨 Refactor, ➕ Add, D-3

#93 [Team] 아이콘 교체
  src/assets/team_BSTeam.svg
  src/assets/team_PM_manufacturingTeam.svg
  src/assets/team_RD.svg
  src/assets/team_RDTeam.svg
  src/assets/team_UXTeam.svg
  src/assets/team_generalAffairsTeam.svg
  src/assets/team_personnelTeam.svg
  src/components/Team/RoleAllSection.jsx
  src/components/Team/RoleCard.jsx
  src/components/Team/RoleSection.jsx
  src/components/Team/Team.module.css
  src/components/Team/TeamIcon.jsx
  src/data/teamData.js
  src/views/Team.jsx
Labels: ✍️ Update, D-3

#96 [Solutions] Lnb, Snb, Func 컴포넌트 수정
  src/assets/solutions_ACS Simulator.png
  src/assets/solutions_ACS.png
  src/assets/solutions_AIMS.png
  src/assets/solutions_CCS.png
  src/assets/solutions_HSMS.png
  src/assets/solutions_IDX Controller.png
  src/assets/solutions_Map Designer.png
  src/assets/solutions_OCS.png
  src/assets/solutions_SCS Simulator.png
  src/assets/solutions_SCS.png
  src/components/Solutions/Func.jsx
  src/components/Solutions/Solutions.module.css
  src/components/Solutions/imageImport.js
Labels: ✨ Feature, 🔨 Refactor, 🔧 fix, ➕ Add

#106 [About] 더미 배너 이미지 추가
  src/assets/about_banner.png
  src/components/About/About.module.css
  src/components/About/BannerImage.jsx
Labels: ✨ Feature, ➕ Add, D-3

#104 [Industries] Industries, Snb, Product 컴포넌트 수정
  src/assets/products_ACS Simulator.png
  src/assets/products_ACS.png
  src/assets/products_AIMS.png
  src/assets/products_CCS.png
  src/assets/products_HSMS.png
  src/assets/products_IDX Controller.png
  src/assets/products_Map Designer.png
  src/assets/products_OCS.png
  src/assets/products_SCS Simulator.png
  src/assets/products_SCS.png
  src/components/Industries/Industries.module.css
  src/components/Industries/Product.jsx
  src/components/Industries/importImage.js
  src/views/Industries.jsx
Labels: ✨ Feature, 🔨 Refactor, 🔧 fix, ➕ Add

#107 [Home] tailwind.config.js추가
  tailwind.config.js
Labels: ✍️ Update, ⚙ Setting, ➕ Add, D-3

#137 [Library] Library 페이지 내용 추가
  src/assets/library_companyBrochure_ko.pdf
  src/components/Library/DownloadSection.jsx
Labels: ✍️ Update, D-3

#126 [Home] - 모바일에서의 효과, width 수정 등 조치
  package-lock.json
  package.json
  src/assets/home_solutions0.png
  src/assets/home_solutions1.png
  src/assets/home_solutions2.png
  src/assets/home_solutions3.png
  src/assets/home_solutions4.png
  src/assets/home_solutions5.png
  src/assets/home_solutions6.png
  src/components/Home/Home.module.css
  src/components/Home/Keywords.jsx
  src/components/Home/Partner.jsx
  src/components/Home/Solutions.jsx
  src/routes/routes.jsx
  vite.config.js
Labels: ✍️ Update, 🔧 fix, ➕ Add, D-3

#132 [Community] - div 삭제 등 레이아웃 일부 수정
  src/components/Admin/Admin.module.css
  src/views/Admin.jsx
  src/views/Community.jsx
Labels: ✍️ Update, 🔧 fix, ➕ Add, D-3

#121 [MachinesDevices] MachinesDevices, Card, FuncChar 컴포넌트 수정
  src/assets/machinesDevices_360.svg
  src/assets/machinesDevices_batteryCharging.svg
  src/assets/machinesDevices_batteryPlus.svg
  src/assets/machinesDevices_carCrash.svg
  src/assets/machinesDevices_conversionPath.svg
  src/assets/machinesDevices_designServices.svg
  src/assets/machinesDevices_detectorAlarm.svg
  src/assets/machinesDevices_editRoad.svg
  src/assets/machinesDevices_eyeglasses.svg
  src/assets/machinesDevices_flexWrap.svg
  src/assets/machinesDevices_forklift.svg
  src/assets/machinesDevices_gridView.svg
  src/assets/machinesDevices_navigation.svg
  src/assets/machinesDevices_precisionManufacturing.svg
  src/assets/machinesDevices_psychology.svg
  src/assets/machinesDevices_qr.svg
  src/assets/machinesDevices_rebase.svg
  src/assets/machinesDevices_timer.svg
  src/assets/machinesDevices_wifi.svg
  src/components/MachinesDevices/Card.jsx
  src/components/MachinesDevices/CradsWrapper.jsx
  src/components/MachinesDevices/Desc.jsx
  src/components/MachinesDevices/FuncChar.jsx
  src/components/MachinesDevices/MachinesDevices.module.css
  src/components/MachinesDevices/imporIcon.js
  src/components/MachinesDevices/importImage.js
  src/data/devicesData.json
  src/data/machinesData.json
  src/views/MachinesDevices.jsx
Labels: ✨ Feature, 🔨 Refactor, 🔧 fix, ➕ Add, D-3

#123 [About] Ci 컴포넌트 로고 이미지 src 변경
  src/assets/about_ci.png
  src/components/About/Ci.jsx
Labels: ✍️ Update, 🔧 fix, ➕ Add, D-3

#125 [Solutions] BannerImage 컴포넌트 높이 수정
  src/components/Solutions/Solutions.module.css
Labels: ✍️ Update, 🎨 Html&css

#129 [History] - History 컴포넌트의 모바일 레이아웃 변경
  src/components/History/History.module.css
  src/components/History/HistoryMobile.jsx
  src/components/History/HistorySlide.jsx
  src/components/History/HistorySwiper.jsx
  src/views/History.jsx
Labels: ✍️ Update, 🎨 Html&css, ➕ Add, D-3

#138 [Contact] 문의유형 아이콘 교체
  src/components/Contact/InquiryInput.jsx
  src/components/Contact/icons/ASIcon.jsx
  src/components/Contact/icons/EtcIcon.jsx
  src/components/Contact/icons/ProductIcon.jsx
  src/components/Contact/icons/PurchaseIcon.jsx
Labels: ✍️ Update, D-3

#147 [home] - 공통 에러 조치
  package-lock.json
  package.json
  src/components/Common/Spinner.jsx
  src/layout/RootLayout.jsx
Labels: ⚙ Setting, 🔧 fix, ➕ Add, D-3

#152 [Home] Spinner 일부 수정 + 메인 페이지 react-helemet 적용
  src/App.jsx
  src/components/Common/Spinner.jsx
  src/layout/RootLayout.jsx
  src/views/Home.jsx
Labels: ✍️ Update, ➕ Add, 🥰 Accessibility, D-3

#145 [Header] Header 컴포넌트의 hover 효과 및 sitemap 레이아웃 수정
  src/assets/header_opensgBlue.png
  src/components/Header/Hamburger.module.css
  src/components/Header/Header.module.css
  src/components/Header/Sitemap.jsx
  src/components/Header/Sitemap.module.css
  src/components/Header/SitemapMobile.jsx
  src/layout/Header.jsx
Labels: ✍️ Update, 🎨 Html&css, D-3

#165 [Industries] 페이지 중앙 정렬, Snb 컴포넌트 색상 변경, Products 컴포넌트 AOS 적용
  package-lock.json
  package.json
  src/components/Industries/Char.jsx
  src/components/Industries/Industries.module.css
  src/components/Industries/Product.jsx
  src/components/Industries/Snb.jsx
  src/views/Industries.jsx
Labels: ✨ Feature, 🎨 Html&css, ➕ Add, D-3

#163 [Footer] 페이스북 이동 링크, ScrollTop 버튼 구현
  src/components/Footer/Footer.module.css
  src/components/Footer/MoveButton.jsx
  src/components/Footer/Side.jsx
  src/components/Footer/icons/FacebookIcon.jsx
  src/components/Footer/icons/ScrollToIcon.jsx
  src/layout/Footer.jsx
Labels: ✨ Feature, ➕ Add, D-3

#176 [Home] - 동영상 배치, 이미지 수정 등 메인 페이지 피드백 반영
  src/assets/home_partner1.png
  src/assets/home_partner2.png
  src/assets/home_partner3.png
  src/assets/home_slogan.mp4
  src/assets/home_slogan.svg
  src/assets/home_solutions0.png
  src/assets/home_solutions1.png
  src/assets/home_solutions2.png
  src/assets/home_solutions3.png
  src/assets/home_solutions4.png
  src/assets/home_solutions5.png
  src/assets/home_solutions6.png
  src/components/Common/Spinner.jsx
  src/components/Home/Home.module.css
  src/components/Home/Partner.jsx
  src/components/Home/Slogan.jsx
  src/components/Home/Solutions.jsx
  src/layout/RootLayout.jsx
  src/views/Home.jsx
  tailwind.config.js
Labels: ✍️ Update, ➕ Add, D-3

#164 [Common] OpenSG 명칭 통일 및 세부 디자인 수정
  index.html
  src/components/Common/BannerSection.jsx
  src/components/Common/BannerSection.module.css
  src/components/Common/TitleSection.jsx
  src/components/Common/TitleSection.module.css
  src/components/Contact/Agreement.jsx
  src/components/Footer/ContactUsSection.jsx
  src/components/Home/Slogan.jsx
  src/components/Home/Universe.jsx
  src/components/Library/DownloadSection.jsx
  src/components/Team/RoleAllSection.jsx
  src/components/Team/Team.module.css
  src/views/About.jsx
  src/views/History.jsx
  src/views/Home.jsx
  src/views/Location.jsx
  src/views/Team.jsx
Labels: ✍️ Update, 🔨 Refactor, 🔧 fix, 🎨 Html&css, D-3

#167 [Library] hover 시 효과 적용
  src/components/Library/DownloadIcon.jsx
  src/components/Library/Library.module.css
Labels: ✍️ Update, 🔨 Refactor, 🎨 Html&css, D-3

#173 [Contact] 소속, 성명 input 추가 및 placeholder 변경
  src/components/Contact/Content.jsx
  src/components/Contact/PersonalInfo.jsx
Labels: ✨ Feature, ✍️ Update, 🔨 Refactor, ➕ Add, D-3

#177 [Team] border-width 변경 및 아이콘 교체
  src/assets/team_BSTeam.svg
  src/assets/team_PM_manufacturingTeam.svg
  src/assets/team_RD.svg
  src/assets/team_RDTeam.svg
  src/assets/team_UXTeam.svg
  src/assets/team_generalAffairsTeam.svg
  src/assets/team_personnelTeam.svg
  src/components/Team/Team.module.css
Labels: ✍️ Update, 🔨 Refactor, 🎨 Html&css, D-3

#178 [Header] Header 및 Sitemap 컴포넌트 기능 및 레이아웃 변경
  package-lock.json
  package.json
  src/components/Header/Header.module.css
  src/components/Header/Sitemap.jsx
  src/components/Header/Sitemap.module.css
  src/components/Header/SitemapDesktop.jsx
  src/components/Header/SitemapMobile.jsx
  src/layout/Header.jsx
Labels: ✍️ Update, 🎨 Html&css, D-3

#181 [Industries] Snb 컴포넌트 버튼 클릭 함수 변경
  src/components/Industries/Snb.jsx
Labels: 🔧 fix, D-3

#179 [Common] 배포 관련 설정 추가
  index.html
  src/App.jsx
  src/main.jsx
  src/routes/routes.jsx
  vite.config.js
Labels: ✍️ Update, ➕ Add, 🥰 Accessibility, D-3

#183 🐛 [Fix] : AOS 제거
  index.html
  package-lock.json
  package.json
  src/components/Industries/Product.jsx
  src/components/Solutions/Char.jsx
  src/views/Industries.jsx
  src/views/Solutions.jsx
Labels: 🐞 Bug, 🔧 fix, D-3

#196 [Community] - padding 등 디자인 일부 수정
  src/components/Community/Community.module.css
Labels: ✍️ Update, 🎨 Html&css, D-3

#203 [History] History 페이지의 연혁 또는 카드 선택 기능 및 키보드 접근성 구현
  src/assets/history_circle.svg
  src/assets/history_circleline.svg
  src/components/History/History.module.css
  src/components/History/HistoryMobile.jsx
  src/components/History/HistoryMobileSlide.jsx
  src/components/History/HistorySlide.jsx
  src/components/History/HistorySwiper.jsx
  src/components/History/YearSlide.jsx
  src/components/History/icons/HistoryCircleIcon.jsx
Labels: ✨ Feature, ✍️ Update, 🥰 Accessibility, D-3

#206 [Location] aos 애니메이션 기능 추가 및 주소 변경
  package-lock.json
  package.json
  src/components/Location/Location.module.css
  src/components/Location/LocationContainer.jsx
  src/views/Location.jsx
Labels: ✍️ Update, 🎨 Html&css, D-3

#198 [Footer] z-index 설정 및 아이콘 크기 조절
  src/components/Footer/Footer.module.css
Labels: 🎨 Html&css, D-3

#199 [Team] 직무소개 디자인 변경
  src/assets/team_RDTeam.svg
  src/components/Team/RoleCard.jsx
  src/components/Team/Team.module.css
  src/views/Team.jsx
Labels: ✍️ Update, 🔨 Refactor, 🎨 Html&css, D-3

#200 [Library] hover 시 효과 변경
  src/components/Library/Library.module.css
Labels: ✍️ Update, 🔨 Refactor, 🎨 Html&css, D-3

#205 [Common] assets 변경
  src/assets/aboutUs_background.png
Labels: ✍️ Update

#208 [Header] 추가된 고객문의 페이지를 위한 header 로직 수정
  src/layout/Header.jsx
Labels: ✍️ Update, D-3

#211 [Location] Location 지도 이미지 및 핀 아이콘에 aos 추가
  src/components/Location/LocationContainer.jsx
  src/components/Location/LocationPinIcon.jsx
  src/views/Location.jsx
Labels: ✨ Feature, ➕ Add, D-3

#212 [Header] Header 컴포넌트의 z-index 수정
  src/components/Header/Header.module.css
Labels: 🔧 fix, 🎨 Html&css, D-3

#223 [Team] 애니메이션 적용 및 중복 렌더링 해결
  src/components/Team/RoleAllSection.jsx
  src/components/Team/RoleCard.jsx
  src/components/Team/RoleSection.jsx
  src/components/Team/TeamLnb.jsx
Labels: ✨ Feature, ✍️ Update, 🔨 Refactor, 🔧 fix, ➕ Add, D-3

#227 [Contact] 로직 병합
  src/views/ContactRe.jsx
Labels: ✍️ Update, 🔨 Refactor, D-3

#225 [Common] 애니메이션 효과 적용
  src/components/Common/BannerSection.jsx
  src/components/Common/TitleSection.jsx
Labels: ✨ Feature, ➕ Add, D-3

#226 [Solutions] 하단 여백 제거 및 Lnb 수정
  src/components/Solutions/Snb.jsx
  src/components/Solutions/Solutions.module.css
  src/views/Solutions.jsx
Labels: 🔧 fix, ➕ Add, D-3

#231 [MachinesDevices] 애니메이션 효과 적용 및 디자인 수정
  src/components/MachinesDevices/CradsWrapper.jsx
  src/components/MachinesDevices/Desc.jsx
  src/components/MachinesDevices/FuncChar.jsx
  src/components/MachinesDevices/MachinesDevices.module.css
Labels: ✨ Feature, ➕ Add, D-3

#230 [Header] 모바일 sitemap 에 framer-motion 적용 및 로직 추가
  package-lock.json
  package.json
  src/components/Header/AboutUsList.jsx
  src/components/Header/AccordionItem.jsx
  src/components/Header/Hamburger.module.css
  src/components/Header/Header.module.css
  src/components/Header/IndustriesSubList.jsx
  src/components/Header/MenuLink.jsx
  src/components/Header/MenuLinkMobile.jsx
  src/components/Header/ServiceAndSolution.jsx
  src/components/Header/Sitemap.module.css
  src/components/Header/SitemapMobile.jsx
  src/components/Header/SmartDeviceSubList.jsx
  src/components/Header/SmartMachineSubList.jsx
  src/components/Header/SolutionsSubList.jsx
  src/components/Header/SupportList.jsx
  src/icons/SitemapArrow.jsx
Labels: ✨ Feature, ➕ Add, D-3

#232 [Home] 솔루션 내 인터랙션 추가
  src/assets/home_partner6.png
  src/assets/home_partner7.png
  src/assets/home_partner8.png
  src/assets/home_products2.png
  src/components/Home/Home.module.css
  src/components/Home/Industries.jsx
  src/components/Home/Partner.jsx
  src/components/Home/Products.jsx
  src/components/Home/Solutions.jsx
  tailwind.config.js
Labels: ✍️ Update, ➕ Add, D-3

#234 [Industries] 이미지 변경 및 AOS, hover 효과 추가
  src/assets/products_ACS Simulator.png
  src/assets/products_ACS.png
  src/assets/products_AIMS.png
  src/assets/products_CCS.png
  src/assets/products_HSMS.png
  src/assets/products_IDX Controller.png
  src/assets/products_Map Designer.png
  src/assets/products_OCS.png
  src/assets/products_SCS Simulator.png
  src/assets/products_SCS.png
  src/components/Industries/Industries.module.css
  src/components/Industries/Product.jsx
  src/components/Industries/Snb.jsx
  src/components/Solutions/SoultionBanner.jsx
  src/views/Industries.jsx
Labels: ✨ Feature, ➕ Add, D-3

#237 [Library] border 두께 및 색상 변경
  src/components/Library/Library.module.css
Labels: ✍️ Update, 🔨 Refactor, 🎨 Html&css, D-3

#236 [About] AOS 적용
  src/components/About/BannerImage.jsx
  src/components/About/Ci.jsx
  src/components/About/Common/Card.jsx
  src/components/About/Common/Palette.jsx
  src/components/About/Vision.jsx
Labels: ✨ Feature, ➕ Add, D-3

#238 [Common] 메타 이미지 수정
  index.html
  public/meta_logo.png
Labels: ✍️ Update, ➕ Add, 🌏 Deploy, 🥰 Accessibility, D-3

#240 [Community] padding 일부 수정
  src/components/Community/Community.module.css
Labels: ✍️ Update, ➕ Add, D-3

#242 [Contact] 체크박스 두께 변경
  src/assets/contact_agreementCheck.svg
  src/components/Contact/Contact.module.css
Labels: ✍️ Update, 🔨 Refactor, 🎨 Html&css, D-3

#241 [Common] 이미지 경로 수정
  index.html
Labels: ✍️ Update, 🔧 fix, D-3

#243 [Solutions] Banner 이미지 변경 및 Simulator 이미지 추가
  src/assets/products_ACS Simulator_Icon.png
  src/assets/products_ACS_Icon.png
  src/assets/products_AIMS_Icon.png
  src/assets/products_CCS_Icon.png
  src/assets/products_HSMS_Icon.png
  src/assets/products_IDX Controller_Icon.png
  src/assets/products_Map Designer_Icon.png
  src/assets/products_OCS_Icon.png
  src/assets/products_SCS Simulator_Icon.png
  src/assets/products_SCS_Icon.png
  src/components/Solutions/Solutions.module.css
  src/components/Solutions/SoultionBanner.jsx
  src/components/Solutions/importImageSolutions.js
  src/views/Industries.jsx
Labels: ✨ Feature, ➕ Add, D-3

#244 [Team] 애니메이션 지연시간 설정 및 지속시간 변경
  src/components/Team/RoleCard.jsx
  src/components/Team/TeamLnb.jsx
Labels: ✍️ Update, 🔨 Refactor, D-3

#245 [Common] TitleSection y축 padding 수정
  src/components/Common/BannerSection.jsx
  src/components/Common/BannerSection.module.css
  src/components/Common/TitleSection.jsx
  src/components/Common/TitleSection.module.css
Labels: ✍️ Update, 🔨 Refactor, 🎨 Html&css, D-3

#246 [Header] Service & Solutions 의 hover 시 메뉴 레이아웃 일부 수정 및 tooltip 애니메이션 추가
  src/components/Header/Header.module.css
  src/components/Header/Sitemap.module.css
  src/components/Header/SitemapDesktop.jsx
  src/components/Header/SitemapMobile.jsx
  src/layout/Header.jsx
Labels: ✍️ Update, 🎨 Html&css, D-3

#247 [Home] CSS 일부 변경
  src/components/Home/Home.module.css
  src/components/Home/Industries.jsx
  src/components/Home/Partner.jsx
  src/components/Home/Slogan.jsx
  src/components/Home/Solutions.jsx
  tailwind.config.js
Labels: ✍️ Update, D-3

#254 [Home] 공통 module.css 생성 및 적용 등
  .prettierrc
  package-lock.json
  package.json
  src/components/Home/Home.module.css
  src/components/Home/Industries.jsx
  src/components/Home/Partner.jsx
  src/components/Home/ProductCard.jsx
  src/components/Home/Products.jsx
  src/components/Home/Slogan.jsx
  src/components/Home/Solutions.jsx
  src/components/Home/Universe.jsx
  src/styles/styles.module.css
  src/views/Home.jsx
Labels: ✍️ Update, 🔨 Refactor, ➕ Add, D-3

#267 [Common] eslint plugins 수정
  .eslintrc.cjs
Labels: 🔧 fix, D-3

#248 [History] 연혁 카드 순서 및 일부 기능 변경
  src/components/History/HistorySwiper.jsx
  src/data/historyData.json
  src/views/History.jsx
Labels: ✨ Feature, ✍️ Update, D-3

#249 [Footer] 회사정보 텍스트 색상 변경 및 유튜브 이동 링크 구현
  src/components/Footer/Footer.module.css
  src/components/Footer/Side.jsx
  src/components/Footer/icons/YoutubeIcon.jsx
Labels: ✨ Feature, ✍️ Update, 🔨 Refactor, 🎨 Html&css, ➕ Add, D-3

#251 [Common] 텍스트 통일성 구축
  src/components/About/Group.jsx
  src/components/About/Vision.jsx
  src/components/Home/Products.jsx
  src/components/Home/Slogan.jsx
  src/components/Home/Solutions.jsx
  src/components/Home/Universe.jsx
  src/data/devicesData.json
  src/data/machinesData.json
  src/data/solutionsData.json
  src/views/Location.jsx
Labels: 🔨 Refactor, D-3

#250 [Location] USA 핀 아이콘 tooltip 내용 변경
  src/components/Location/Location.module.css
  src/views/Location.jsx
Labels: ✍️ Update, 🎨 Html&css, D-3

#252 [Contact] label width 조정 및 CTO 이메일 연결
  src/components/Contact/Contact.module.css
  src/data/emailConfig.js
  src/views/Contact.jsx
  src/views/ContactRe.jsx
Labels: ✨ Feature, ✍️ Update, 🔧 fix, 🎨 Html&css, ➕ Add, D-3

#253 [Team] 애니메이션 횟수 제한
  src/components/Team/RoleCard.jsx
Labels: ✍️ Update, 🔨 Refactor, D-3

#262 [Solutions] Lnb 컴포넌트 수정
  src/views/Solutions.jsx
Labels: 🔧 fix, D-3

#260 [Community] 공통 모듈 css 적용 등
  src/components/Admin/Admin.module.css
  src/components/Community/ButtonSection.jsx
  src/components/Community/Community.module.css
  src/components/Community/ContentsSection.jsx
  src/components/Community/InputSection.jsx
  src/components/Community/ListButtons.jsx
  src/components/Community/Notice.jsx
  src/components/Community/NoticeList.jsx
  src/components/Community/NoticeSection.jsx
  src/styles/styles.module.css
  src/views/Admin.jsx
  src/views/Community.jsx
  src/views/CommunityDetail.jsx
  src/views/CommunityForm.jsx
Labels: 🗑️ Delete, ✍️ Update, ➕ Add, D-3

#263 [Industries] TitleSection 컴포너트 subTitle 앞글자 대문자 변경
  src/views/Industries.jsx
Labels: 🔧 fix, D-3

#261 [AOS] Industries, Solutions, About, Machines&Devices 페이지 AOS 변경
  src/components/About/BannerImage.jsx
  src/components/About/Common/Card.jsx
  src/components/About/Common/Palette.jsx
  src/components/Industries/Product.jsx
  src/components/MachinesDevices/Desc.jsx
  src/components/MachinesDevices/FuncChar.jsx
  src/components/Solutions/Char.jsx
  src/components/Solutions/Effect.jsx
  src/components/Solutions/Func.jsx
  src/views/About.jsx
  src/views/Industries.jsx
  src/views/MachinesDevices.jsx
  src/views/Solutions.jsx
Labels: 🔨 Refactor, D-3

#264 [Solutions, Industires] industriesData.json, solutionsData.json 변경
  src/components/Solutions/Char.jsx
  src/data/industriesData.js
  src/data/solutionsData.json
Labels: 🔧 fix, D-3

#269 [Common] title 변경 등
  index.html
  package-lock.json
  package.json
Labels: ✍️ Update, 🔧 fix, ➕ Add, D-3

#268 [CSS] Industries, Solutions, About, Machines&Devices 컴포넌트 공통 module.css로 병합 및 코드 리팩토링
  src/components/About/About.module.css
  src/components/About/BannerImage.jsx
  src/components/About/Ci.jsx
  src/components/About/Common/Card.jsx
  src/components/About/Common/Palette.jsx
  src/components/About/Common/Title.jsx
  src/components/About/Group.jsx
  src/components/About/Vision.jsx
  src/components/Industries/Char.jsx
  src/components/Industries/Industries.module.css
  src/components/Industries/Product.jsx
  src/components/Industries/Snb.jsx
  src/components/Industries/industriesProductImage.js
  src/components/MachinesDevices/Card.jsx
  src/components/MachinesDevices/CradsWrapper.jsx
  src/components/MachinesDevices/Desc.jsx
  src/components/MachinesDevices/FuncChar.jsx
  src/components/MachinesDevices/MachinesDevices.module.css
  src/components/MachinesDevices/machinesDevicesFuncCharImage.js
  src/components/MachinesDevices/machinesDevicesProuductImage.js
  src/components/Solutions/Char.jsx
  src/components/Solutions/Effect.jsx
  src/components/Solutions/Func.jsx
  src/components/Solutions/Lnb.jsx
  src/components/Solutions/Snb.jsx
  src/components/Solutions/Solutions.module.css
  src/components/Solutions/SoultionBanner.jsx
  src/components/Solutions/solutionsBannerImage.js
  src/components/Solutions/solutionsFuncImage.js
  src/styles/styles.module.css
  src/views/About.jsx
  src/views/Industries.jsx
  src/views/MachinesDevices.jsx
  src/views/Solutions.jsx
Labels: ✍️ Update, 🔨 Refactor, 🎨 Html&css, D-3

#272 [Contact] 고객문의 메일 발송 시 발생하는 페이지 오류 해결
  src/views/Contact.jsx
  src/views/ContactRe.jsx
Labels: ✍️ Update, 🔧 fix, D-3

#275 [Common] module.css 파일 통합 및 주석 추가
  src/components/Common/BannerSection.jsx
  src/components/Common/BannerSection.module.css
  src/components/Common/TitleSection.jsx
  src/components/Common/TitleSection.module.css
  src/components/Contact/Agreement.jsx
  src/components/Contact/Contact.module.css
  src/components/Contact/Content.jsx
  src/components/Contact/ContentRe.jsx
  src/components/Contact/FillingInput.jsx
  src/components/Contact/InquiryInput.jsx
  src/components/Contact/InquiryType.jsx
  src/components/Contact/NoticeContent.jsx
  src/components/Contact/PersonalInfo.jsx
  src/components/Contact/PersonalInfoRe.jsx
  src/components/Contact/icons/ASIcon.jsx
  src/components/Contact/icons/EtcIcon.jsx
  src/components/Contact/icons/ProductIcon.jsx
  src/components/Contact/icons/PurchaseIcon.jsx
  src/components/Footer/ContactUsSection.jsx
  src/components/Footer/Footer.module.css
  src/components/Footer/MoveButton.jsx
  src/components/Footer/OfficeInfoSection.jsx
  src/components/Footer/Side.jsx
  src/components/Footer/icons/FacebookIcon.jsx
  src/components/Footer/icons/ScrollToIcon.jsx
  src/components/Footer/icons/YoutubeIcon.jsx
  src/components/Library/DownloadCard.jsx
  src/components/Library/DownloadIcon.jsx
  src/components/Library/DownloadSection.jsx
  src/components/Library/Library.module.css
  src/components/Team/RoleCard.jsx
  src/components/Team/RoleSection.jsx
  src/components/Team/Team.module.css
  src/components/Team/TeamLnb.jsx
  src/layout/Footer.jsx
  src/styles/styles.module.css
  src/views/Contact.jsx
  src/views/ContactFail.jsx
  src/views/ContactRe.jsx
  src/views/ContactSuccess.jsx
  src/views/Library.jsx
  src/views/Team.jsx
Labels: ✍️ Update, 🎨 Html&css, D-3

#273 [Styles] 공통 Header, 오시는 길 페이지, 연혁 페이지 css 전체 통합 및 주석 설명 추가
  src/components/Header/AboutUsList.jsx
  src/components/Header/AccordionItem.jsx
  src/components/Header/Hamburger.module.css
  src/components/Header/Header.module.css
  src/components/Header/IndustriesSubList.jsx
  src/components/Header/MenuLink.jsx
  src/components/Header/MenuLinkMobile.jsx
  src/components/Header/ServiceAndSolution.jsx
  src/components/Header/Sitemap.module.css
  src/components/Header/SitemapDesktop.jsx
  src/components/Header/SitemapMobile.jsx
  src/components/Header/SmartDeviceSubList.jsx
  src/components/Header/SmartMachineSubList.jsx
  src/components/Header/SolutionsSubList.jsx
  src/components/Header/SupportList.jsx
  src/components/History/History.module.css
  src/components/History/HistoryMobile.jsx
  src/components/History/HistoryMobileSlide.jsx
  src/components/History/HistorySlide.jsx
  src/components/History/HistorySwiper.jsx
  src/components/History/YearSlide.jsx
  src/components/Location/Location.module.css
  src/components/Location/LocationContainer.jsx
  src/components/Location/LocationPinIcon.jsx
  src/icons/SitemapArrow.jsx
  src/layout/Header.jsx
  src/styles/styles.module.css
  src/views/History.jsx
  src/views/Location.jsx
Labels: 🎨 Html&css, D-3
