Repository ReOpenSG/ReOpenSG, pull requests merged in 2024-01, with the labels that each got.

#276 [Contact] 고객문의 페이지 코드 되돌리기
  src/views/Contact.jsx
  src/views/ContactRe.jsx
Labels: ✍️ Update, D-3

#277 [Home] - 한영변환 기능 추가
  package-lock.json
  src/App.jsx
  src/components/Footer/ContactUsSection.jsx
  src/components/Footer/OfficeInfoSection.jsx
  src/components/Home/Industries.jsx
  src/components/Home/Partner.jsx
  src/components/Home/ProductCard.jsx
  src/components/Home/Products.jsx
  src/components/Home/Slogan.jsx
  src/components/Home/Solutions.jsx
  src/components/Home/Universe.jsx
  src/layout/Header.jsx
  src/locales/en/footer.json
  src/locales/en/home.json
  src/locales/en/index.js
  src/locales/i18n.js
  src/locales/index.js
  src/locales/ko/footer.json
  src/locales/ko/home.json
  src/locales/ko/index.js
  src/recoil/atoms/languageStore.js
  src/styles/styles.module.css
  src/views/Home.jsx
Labels: ✨ Feature, ✍️ Update, ➕ Add, D-3

#279 [Common] - 페이지 로딩 문제 해결을 위한 AOS 초기화 코드 병합
  src/App.jsx
  src/components/About/Group.jsx
  src/components/Common/BannerSection.jsx
  src/components/Common/TitleSection.jsx
  src/components/Footer/Side.jsx
  src/components/Header/SitemapDesktop.jsx
  src/components/Header/SitemapMobile.jsx
  src/components/Location/LocationContainer.jsx
  src/components/Location/LocationPinIcon.jsx
  src/components/Solutions/Effect.jsx
  src/components/Solutions/SoultionBanner.jsx
  src/components/Team/RoleCard.jsx
  src/components/Team/TeamLnb.jsx
  src/layout/Header.jsx
  src/locales/ko/home.json
  src/views/About.jsx
  src/views/Home.jsx
  src/views/Industries.jsx
  src/views/Location.jsx
  src/views/MachinesDevices.jsx
  src/views/Solutions.jsx
Labels: D-3

#281 [Industries] 산업분아별 링크 이동 시 데이터 변경
  src/views/Industries.jsx
Labels: 🔧 fix
